import { Metadata } from "next"
import { usePathname } from "next/navigation"


export const metadata: Metadata = {
    title:'Search',
    description: 'Generated by create next app',
  }

export default function Search() {


    return (
      <div>
         search
      </div>
     
      
    )
  }
  