import { Header } from '@/components/header'
import { Menu } from '@/components/menu/menu'
import { Player } from '@/components/player'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='globalBody'>     
        <div className='globalHead'> 
        <Header />
        </div>
      <  div className='globalMenu'>  <Menu /></div>
      
      <div className='globalChildren'>{children}</div>
      <div className='globalPlayer'>
        <Player />
      </div>
      
      </body> 
    </html>
  )
}
