'use client';
import { Menu } from '@/components/menu/menu';
import { Player } from '@/components/player';

import './globals.css';
import { Header } from '@/components/HeroHeader';
import back from '../public/background.svg';
import { ContextAudio, ContextPlayer } from '@/hook/context';
import { useEffect, useReducer, useRef } from 'react';
import reducer from '@/hook/reducer';

type GlobalContent = {
    songs: string;
    state: boolean;
    audio: string;
    allAudio:string;
};
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const initialState: GlobalContent = {
    songs: ' https://project-49di.onrender.com/images\\1701954196234.mp3',
    state: true,
    audio: '',
    allAudio:''
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const [value, dispatch] = useReducer(reducer, initialState);
    const  audioRef=useRef(null);
    useEffect(() => {
        //
        document.title = 'main';
    }, []);
    return (
        <html lang="en">
            <body
                className="globalBody"
                style={{ backgroundImage: `url(${back})` }}
            >
                <div className="globalHead">
                    <Header />
                </div>
                <div className="globalMenu">
                    {' '}
                    <Menu />
                </div>
                <ContextAudio.Provider value={audioRef}>
                <ContextPlayer.Provider value={[value, dispatch]}>
                    <div className="globalChildren">{children}</div>
                    <div className="globalPlayer">
                        <Player />
                    </div>
                </ContextPlayer.Provider>
                </ContextAudio.Provider>
            </body>
        </html>
    );
}
