"use client"
import { Menu } from '@/components/menu/menu'
import { Player } from '@/components/player'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/HeroHeader'
import back from '../public/background.svg'
import { ContextPlayer } from '@/hook/context'
import { useEffect, useReducer } from 'react'
import reducer from '@/hook/reducer'


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
const [value,dispatch]= useReducer(reducer,false)
  useEffect(() => {
  //
  document.title = 'main';
  
}, []);
  return (
    <html lang="en">
      <body className='globalBody' style={{ backgroundImage: `url(${back})` }}>     
        <div className='globalHead' > 
        <Header />
        </div>
      <  div className='globalMenu' >  <Menu /></div>
      <ContextPlayer.Provider value={[value,dispatch]}>
      <div className='globalChildren'>{children}</div>
      <div className='globalPlayer'>
        <Player />
      </div>
      </ContextPlayer.Provider >
      </body> 
    </html>
  )
}
